### ISSUE TITLE
BISP student can not find the option `Organize and preview your upcoming semester`

### ISSUE THREAD

**Issue by recolic** [ziyaointl/Schedule-Exporter#1]
Hi I'm a BISP international student. After opening `https://calcentral.berkeley.edu/academics`, I can not find an entry saying `Organize and preview your upcoming semester`. Here's my screenshots:

snap-0121-165649.png                                                                                                                                        100%  132KB   2.4MB/s   00:00    
Pushed to https://recolic.net/tmp/snap-0121-165649.png
snap-0121-165655.png                                                                                                                                        100%   46KB   1.2MB/s   00:00    
Pushed to https://recolic.net/tmp/snap-0121-165655.png

**Comment by ziyaointl** [comment]
Hi @recolic!

Thank you for using this extension! It does seem like your calcentral page does not contain a link to the schedule planner. Since this extension gathers all the information from the planner website, I can't do much without rewriting the whole extension.
However, I do believe that the link to schedule planner is universal for everyone. After logging into calcentral, you can try pasting https://calcentral.berkeley.edu/college_scheduler/student/UGRD/2192 into the address bar and hit enter. You may be redirected to the schedule planner. Let me know if it worked for you!
